[watch]
watch = ["src/"]

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "npm install"]

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "npx @tailwindcss/cli -i input.css -o style/output.css"]
